# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - format_analyzer_tests:
    - group:
      - command: ./compile_protos.sh
      - dartfmt
      - dartanalyzer: --fatal-warnings .
      dart: [stable]
