language: dart

before_install:
  - sudo apt-get install -y protobuf-compiler
  - cd benchmark/query_benchmark; pub get; ./compile-protos.sh

dart:
- dev

dart_task:
- test: --platform vm
- test: --platform chrome
- dartfmt
- dartanalyzer
# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
