include: package:pedantic/analysis_options.yaml

analyzer:
  # TODO(sigurdm): `benchmarks` should be moved out of the protobuf folder.
  exclude: [benchmarks/**]

linter: 
  rules:
    prefer_spread_collections: false
