# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format:
    - group:
      - dartanalyzer: --fatal-infos --fatal-warnings .
      dart: [dev]
  - analyzer_and_format_stable:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-warnings .
      dart: [stable]
  - unit_test:
    - group:
      - test
      dart: [stable, dev]