# See https://github.com/dart-lang/mono_repo for details
stages:
  - format_analyze:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - format
      - analyze: --fatal-infos
      dart: [dev]
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - analyze
      dart: [2.10.5]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test
      dart: [2.10.5, dev]
