name: protoc_plugin
version: 19.1.0
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.6.0-dev.8.1 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  path: ^1.0.0
  protobuf: '>=0.14.4 <2.0.0'
  dart_style: ^1.0.6

dev_dependencies:
  test: ^1.3.0

executables:
  protoc-gen-dart: protoc_plugin

dependency_overrides: {
  protobuf: {
    path: '../protobuf'
  }
}
